name: Scully Publish

on:
  push:
    branches:
      - master
      - test-new-deploy-action-version

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cmgriffing/scully-gh-pages-action@v7-test1
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          build-args: --prod
          scully-args: --nw
